## Jupyter 단축키
• Shift+enter (실행하고 다음 셀로 넘어감)  
• dd (현재 셀 삭제)  
• a (위에 새로운 셀 생성)   
• b (아래에 새로운 셀 생성)  
• Ctrl+shift+ - (minus) : 편집모드에서 현재 커서를 기준으로 셀 나눔  
• Shift+m : 셀 병합 (커맨드모드에서 병합하고자 하는 첫번째 셀에서) 


## 1. import, seed, print 세팅

In [1]:
import numpy as np
np.random.seed(12345)
import matplotlib.pyplot as plt
plt.rc("figure", figsize=(10, 6))
np.set_printoptions(precision=4, suppress=True)  # 부동소수점 4자리까지, 과학적 표기법

## 2. 효율성 확인

In [2]:
import numpy as np

my_arr = np.arange(1_000_000)
my_list = list(range(1_000_000))

In [3]:
%timeit my_arr2 = my_arr * 2
%timeit my_list2 = [x * 2 for x in my_list]

728 µs ± 24 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
22.3 ms ± 223 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


##  3. ndarray-연산, 크기, 모양, 데이터타입

In [4]:
import numpy as np
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [5]:
data * 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [6]:
data + data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

#### **중요!**  크기, 타입, 모양

In [10]:
# 크기
data.size

6

In [11]:
# 모양
data.shape

(2, 3)

In [12]:
# 데이터 타입
data.dtype

dtype('float64')

In [13]:
# 차원
data.ndim

2

## 4. **중요!** ndarray-다른 방법으로 생성하기

In [42]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [43]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [49]:
np.ones((3, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [51]:
arr2 = np.array([[1,2,3,4,5], [6,7,8,9,10]])

In [52]:
np.zeros_like(arr2)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [54]:
np.empty((2, 3, 2))

array([[[-0.,  2.],
        [ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.],
        [-0.,  0.]]])

In [55]:
np.full((2,3,2),2)

array([[[2, 2],
        [2, 2],
        [2, 2]],

       [[2, 2],
        [2, 2],
        [2, 2]]])

In [56]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [57]:
# 단위행렬 만들기
# np.eye(N(행), M=None(열), k=0(대각선위치), dtype=<class 'float'>, order='C')
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [58]:
# 단위행렬 만들기
# np.identity(행과 열의 수, dtype=None)
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

## 5. ndarray-자료형, 형변환 astype

In [27]:
# np.array(배열데이터, 데이터타입(명시x-추론하여 저장))
arr1 = np.array([1, 2, 3], dtype=float)

In [28]:
arr2 = np.array([1, 2, 3], dtype=int)

In [29]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

In [30]:
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [31]:
arr1.dtype

dtype('float64')

In [32]:
arr2.dtype

dtype('int32')

In [33]:
arr = np.array([1, 2, 3, 4, 5])

In [34]:
arr.dtype

dtype('int64')

In [35]:
# 형변환 astype
float_arr = arr.astype(np.float64)

In [36]:
float_arr

array([1., 2., 3., 4., 5.])

In [37]:
float_arr.dtype

dtype('float64')

In [38]:
arr=np.array([1+2j,3+4j],dtype=np.complex64)

In [39]:
arr

array([1.+2.j, 3.+4.j], dtype=complex64)

In [59]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [60]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

## 6. 형변환 astype의 활용

In [61]:
# 소숫점 삭제
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [63]:
numeric_strings = np.array(["1.25", "-9.6", "42"], dtype=np.string_)
print(numeric_strings)
numeric_strings.astype(float)

[b'1.25' b'-9.6' b'42']


array([ 1.25, -9.6 , 42.  ])

In [64]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [65]:
# 13p
# 본인의 태어난 연도, 키, 시력을 float32타입의 배열로 만들고 
# astype을 통해서 float 64, int 32형으로변환해보자.
info = np.array([1998, 170.4, 1.0], dtype=np.float32)
print(info)
print(info.astype(np.float64))
info.astype(np.int32)

[1998.   170.4    1. ]
[1998.   170.4    1. ]


array([1998,  170,    1], dtype=int32)

## 7. ndarray-산술 연산

### 원소별 개산, 브로드캐스팅

In [66]:
arr0=np.array([[1,2,3],[4,5,6]])

In [68]:
arr0+np.array(3)    # 크기가 다르면 브로드캐스팅 (각각 맞춰 더하기)

array([[4, 5, 6],
       [7, 8, 9]])

In [69]:
arr0+np.array([1,2,3])

array([[2, 4, 6],
       [5, 7, 9]])

In [70]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [71]:
arr * arr   # 크기가 같으면 동일한 배열의 원소간 계산

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [72]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [73]:
1 / arr

array([[1.    , 0.5   , 0.3333],
       [0.25  , 0.2   , 0.1667]])

In [74]:
arr ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [75]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
print(arr2)
arr2 > arr

[[ 0.  4.  1.]
 [ 7.  2. 12.]]


array([[False,  True, False],
       [ True, False,  True]])

In [79]:
# 15p
# 태어난 연도가 2000보다 큰지,키가175보 다큰지,시력이1.0보다 높은지에 대해 
# 비교연산을 통해 bool type으로 반환해보자
info = np.array([1998, 170, 1.1])
arr = np.array([2000, 175, 1.0])
info > arr

array([False, False,  True])

## 8. **중요!** ndarray-색인과 슬라이싱 기초

In [155]:
# 넘파이 배열의 슬라이스는 뷰 (view) 이다.
# 넘파이 배열의 슬라이스와 원본 배열은 서로에게 영향을 줌
arr = np.arange(10)
print(arr)
print(arr[5])
print(arr[5:8])
# 슬라이스의 수정
arr[5:8] = 12
# 슬라이스 수정에 따라 원본배열도 수정됨
print("arr : ", arr)

[0 1 2 3 4 5 6 7 8 9]
5
[5 6 7]
arr :  [ 0  1  2  3  4 12 12 12  8  9]


In [156]:
# 파이썬 리스트의 슬라이스는 원본 배열과 연관 X
list_a     = list(range(10))
list_slice = list_a[5:8]
list_slice = [12,12,12]
print("list_a : ",list_a)

list_a :  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [157]:
# 넘파이 배열의 슬라이스을 수정하면 원본배열도 수정됨
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [158]:
arr_slice[1] = 12345
print("arr_slice : ", arr_slice)
arr

arr_slice :  [   12 12345    12]


array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [159]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [160]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

### 2차원 ndarray-괄호로 구분, 쉼표로 구분

- 쉼표로구분시,축을 따라 선택영역 내의 원소를 선택한다.    
- 괄호로 구분시, 리스트처럼 축의 개념 없이 원소의 나열로 이해  
- 특정 인덱스를 선택시, 차원이 작아진다.  

In [161]:
arr2d[0][2]

3

In [162]:
arr2d[0, 2] 

3

### 3차원 ndarray-괄호로 구분, 쉼표로 구분

In [93]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [152]:
print(arr3d[0][:][1])  # 0번째 차원의 1번째 행의 2번째 열 (0번부터 시작)
arr3d[0,:,1]

[4 5 6]


array([2, 5])

In [147]:
print(arr3d[0][1][2])
arr3d[0,1,2]

6


6

In [98]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [99]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [100]:
arr3d[1, 0]

array([7, 8, 9])

In [101]:
x = arr3d[1]
print(x)
x[0]

[[ 7  8  9]
 [10 11 12]]


array([7, 8, 9])

In [105]:
# 16p
ex = np.array([[[1,2,3,],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
# 차원
print(ex.ndim)
# 모양
print(ex.shape)

3
(3, 2, 3)


In [106]:
# ex[1][1] = 1000
ex[1, 1] = 1000
ex

array([[[   1,    2,    3],
        [   4,    5,    6]],

       [[   7,    8,    9],
        [1000, 1000, 1000]],

       [[  13,   14,   15],
        [  16,   17,   18]]])

## 10. **중요** ndarray-슬라이스로 선택하기

In [107]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [108]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

### 다차원 슬라이싱

In [109]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [110]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [120]:
# 모든차원에서 0행, 1행까지
arr2d[:][:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [121]:
# arr [(차원 인덱스(3차이상)), 행의 인덱스, 열의 인덱스]
arr2d[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [124]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [125]:
print(list_a)
print(list_a[:2])
list_a[:2][1:]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1]


[1]

### 인덱스 선택시 차원이 작아짐

In [127]:
lower_dim_slice = arr2d[1, :2]

In [128]:
lower_dim_slice

array([4, 5])

In [129]:
lower_dim_slice.shape

(2,)

### 두 결과 비교 (차원 축소, 유지 차이)

In [130]:
arr2d[:2, 2]

array([3, 6])

In [131]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [132]:
arr2d[:,0]

array([1, 4, 7])

In [133]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [164]:
# 18p
ex = np.array([[[1,2,3,],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
print(ex.shape)
old_value = ex.copy()

(3, 2, 3)


In [165]:
ex[:2, :, 0] = 1000
ex

array([[[1000,    2,    3],
        [1000,    5,    6]],

       [[1000,    8,    9],
        [1000,   11,   12]],

       [[  13,   14,   15],
        [  16,   17,   18]]])

In [166]:
ex = old_value
ex[:,0, 1] = 1000
ex

array([[[   1, 1000,    3],
        [   4,    5,    6]],

       [[   7, 1000,    9],
        [  10,   11,   12]],

       [[  13, 1000,   15],
        [  16,   17,   18]]])