## 선형회귀 (목적변수는 Sales)

### 1 (a). advertising1.csv와 advertising2.csv를 pd.read_csv를 통해서 load하여  advertising1, advertising2의 이름으로 할당하세요. 

In [449]:
import pandas as pd

In [450]:
advertising1 = pd.read_csv('advertising/advertising1.csv')
advertising2 = pd.read_csv('advertising/advertising2.csv')

### 1.(b) 두 데이터를 advertising의 이름으로 병합하세요, 병합 시에 ignore_index 옵션을 활용하여, 0~199까지 되게 하세요.

In [451]:
advertising = pd.concat([advertising1, advertising2], ignore_index=True)
advertising

TV  Radio  Newspaper  Sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3   12.0
3    151.5   41.3       58.5   16.5
4    180.8   10.8       58.4   17.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1   14.0
197  177.0    9.3        6.4   14.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   18.4

[200 rows x 4 columns]

### 1.(c) advertising의 각 피처가 표준정규분포를 따르도록, 정규화를하세요.

In [452]:
from sklearn.preprocessing import StandardScaler
import numpy as np

# 표준 스케일링 (표준정규분포 따르도록)
scaler = StandardScaler()

sales = np.array(advertising.loc[:,"Sales"])
advertising = advertising.loc[:,["TV", "Radio", "Newspaper"]]

advertising = scaler.fit_transform(advertising)
advertising

/opt/homebrew/lib/python3.11/site-packages/sklearn/utils/validation.py:767: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():
/opt/homebrew/lib/python3.11/site-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/opt/homebrew/lib/python3.11/site-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
/opt/homebrew/lib/python3.11/site-packages/sklearn/utils/validation.py:767: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  i

array([[ 9.69852266e-01,  9.81522472e-01,  1.77894547e+00],
       [-1.19737623e+00,  1.08280781e+00,  6.69578760e-01],
       [-1.51615499e+00,  1.52846331e+00,  1.78354865e+00],
       [ 5.20496822e-02,  1.21785493e+00,  1.28640506e+00],
       [ 3.94182198e-01, -8.41613655e-01,  1.28180188e+00],
       [-1.61540845e+00,  1.73103399e+00,  2.04592999e+00],
       [-1.04557682e+00,  6.43904671e-01, -3.24708413e-01],
       [-3.13436589e-01, -2.47406325e-01, -8.72486994e-01],
       [-1.61657614e+00, -1.42906863e+00, -1.36042422e+00],
       [ 6.16042873e-01, -1.39530685e+00, -4.30581584e-01],
       [-9.45155670e-01, -1.17923146e+00, -2.92486143e-01],
       [ 7.90028350e-01,  4.96973404e-02, -1.22232878e+00],
       [-1.43908760e+00,  7.99208859e-01,  1.62704048e+00],
       [-5.78501712e-01, -1.05768905e+00, -1.07502697e+00],
       [ 6.66253447e-01,  6.50657027e-01,  7.11007392e-01],
       [ 5.64664612e-01,  1.65000572e+00,  1.02862691e+00],
       [-9.25304978e-01,  9.00494200e-01

### 1.(d) 학습데이터와 테스트데이터를 4:1로 나누세요

In [453]:
from sklearn.model_selection import train_test_split
import numpy as np

X_train, X_test, y_train, y_test = train_test_split(advertising, sales,test_size=0.2,random_state=1234)
y_train.shape

(160,)

### 2.(a) 학습데이터를 통해 정규방정식를 통한 선형회귀를 수행하세요. 

In [454]:
n_train, n_test = X_train.shape[0], X_test.shape[0]

X_train = np.append(np.ones((n_train, 1)), X_train, axis=1)
w = np.linalg.inv(X_train.T @ X_train) @ X_train.T @ y_train     

y_pred_train = X_train @ w
y_pred_train 

array([18.66276778, 10.34126748, 17.02664714, 16.53536081, 12.4448438 ,
       21.15644462, 19.57058564, 10.92073978, 14.73445112, 17.55464266,
       24.36509075, 18.93682852,  9.99557176,  7.96016874, 17.08331696,
       14.27483165, 16.13836967, 21.26621204, 18.17506307, 19.66636447,
       17.07481581,  8.9629038 , 17.31511818,  9.73770068,  8.81449982,
       23.57297916, 12.08349484,  6.59841865, 19.70811591, 21.82033987,
       18.26502449,  8.5192422 , 16.55604477, 21.1090306 , 13.12045908,
       23.61947622, 13.88427134, 23.79324685, 20.90793983, 14.20646514,
       10.79987667, 13.87711788, 11.96770598,  9.79592311,  9.87928983,
       19.14739303, 23.17593416, 20.46275103,  9.50325694,  8.88644885,
        5.43730355,  7.51366978,  8.14651027,  7.27250528,  7.34565127,
       18.16033009, 12.70349327, 16.67093431, 12.53210915,  9.85220322,
       11.07783718, 21.40544245, 17.43785449, 11.32596333, 10.93930709,
       20.31585088, 16.35438753, 20.95477009, 13.95092498,  9.39

### 2.(b) 테스트 데이터 셋에 대해 mean_absolute_error와 mean_squared_error를 계산하세요.

In [455]:
import numpy as np  

X_test = np.append(np.ones((n_test, 1)), X_test, axis=1)
y_pred = X_test @ w    # 테스트 데이터의 예측값
# MAE
print('테스트 데이터셋 MAE:',np.abs(y_pred - y_test).mean())
# MSE
print('테스트 데이터셋 MSE:',((y_pred - y_test)**2).mean())

테스트 데이터셋 MAE: 1.2825361296036224
테스트 데이터셋 MSE: 3.025876484301782


### 2.(c) 학습데이터를 통해 경사하강법을 통한 선형회귀를 수행하세요. 

In [456]:
from sklearn.linear_model import SGDRegressor

def gradient_descent(x, y, theta, alpha, numIterations):
    xTrans    = x.transpose()   
    cost_list = []
    for i in range(0, numIterations): 
        hypothesis = np.dot(x, theta)   # 가설함수로 예측값 구하기
        diff       = hypothesis - y     # 예측값과 실제값의 차이
        loss       = np.sum(diff ** 2) / x.shape[0] # 손실함수
        gradient   = np.dot(xTrans, diff)*2  / x.shape[0] # 그래디언트=손실함수의 미분(2, 1)

        # 경사하강법으로 계수 업데이트
        theta      = theta -alpha * gradient  # 경사하강법으로 계수 업데이트
        if i% 250 == 0: 
            cost_list.append(loss)
    return theta, cost_list     # 하이퍼파라미터, 손실값 리턴


numIterations = 10000    # 하이퍼파라미터 업데이트 횟수 (많을수록 훈련데이터의 답 정확하게 예측)
alpha         = 0.01  # 스텝 사이즈
theta         = np.ones(X_train.shape[1]) # 초기 하이퍼 파라미터 (w)
theta, cost_list = gradient_descent(X_train, y_train, theta, alpha, numIterations)
theta

array([15.26480382,  4.68737506,  1.4924404 ,  0.08615097])

### 2.(d) 테스트 데이터 셋에 대해 mean_absolute_error와 mean_squared_error를 계산하세요.

In [457]:
y_predict = np.dot(X_test, theta) # 테스트 데이터의 예측값

print('테스트 데이터셋 MAE:', np.abs(y_pred - y_test).mean())
print('테스트 데이터셋 MSE:',((y_pred - y_test)**2).mean())

테스트 데이터셋 MAE: 1.2825361296036224
테스트 데이터셋 MSE: 3.025876484301782


## 로지스틱 회귀 (survivied가 목적변수)

### 3.(a) train1.csv~train4.csv를 결합하세요. 

In [458]:
train1 = pd.read_csv('titanic/train1.csv')
train2 = pd.read_csv('titanic/train2.csv')
train3 = pd.read_csv('titanic/train3.csv')
train4 = pd.read_csv('titanic/train4.csv')

train = pd.concat([train1, train2, train3, train4], ignore_index=True)
train

PassengerId  Survived  Pclass  \
0               1       0.0     3.0   
1               2       1.0     1.0   
2               3       1.0     3.0   
3               4       1.0     1.0   
4               5       0.0     3.0   
...           ...       ...     ...   
1777          887       NaN     NaN   
1778          888       NaN     NaN   
1779          889       NaN     NaN   
1780          890       NaN     NaN   
1781          891       NaN     NaN   

                                                   Name     Sex   Age  SibSp  \
0                               Braund, Mr. Owen Harris    male  22.0    1.0   
1     Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0    1.0   
2                                Heikkinen, Miss. Laina  female  26.0    0.0   
3          Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0    1.0   
4                              Allen, Mr. William Henry    male  35.0    0.0   
...                                                 ...     ...   ...    ...   
1777                                                NaN     NaN   NaN    NaN   
1778                                                NaN     NaN   NaN    NaN   
1779                                                NaN     NaN   NaN    NaN   
1780                                                NaN     NaN   NaN    NaN   
1781                                                NaN     NaN   NaN    NaN   

      Parch      Ticket   Fare Cabin Embarked  
0       NaN         NaN    NaN   NaN      NaN  
1       NaN         NaN    NaN   NaN      NaN  
2       NaN         NaN    NaN   NaN      NaN  
3       NaN         NaN    NaN   NaN      NaN  
4       NaN         NaN    NaN   NaN      NaN  
...     ...         ...    ...   ...      ...  
1777    0.0      211536  13.00   NaN        S  
1778    0.0      112053  30.00   B42        S  
1779    2.0  W./C. 6607    NaN   NaN        S  
1780    0.0      111369  30.00  C148        C  
1781    0.0      370376   7.75   NaN        Q  

[1782 rows x 12 columns]

### 3.(b) cabin 피처는 삭제, Age의 결측치는 다른 Age의 평균값으로 대체,  Embarked의 결측치는 S로 대체, 피처중에서 object 타입의 피처는 삭제하세요.

In [459]:
train = train.drop(columns=['Cabin'])
train['Age'] = train['Age'].fillna(train['Age'].mean())
train['Embarked'] = train['Embarked'].fillna('S')

for col in train.columns:
    if train[col].dtype == 'object':
        print(col)
        train = train.drop(columns=[col])

train

Name
Sex
Ticket
Embarked


PassengerId  Survived  Pclass        Age  SibSp  Parch   Fare
0               1       0.0     3.0  22.000000    1.0    NaN    NaN
1               2       1.0     1.0  38.000000    1.0    NaN    NaN
2               3       1.0     3.0  26.000000    0.0    NaN    NaN
3               4       1.0     1.0  35.000000    1.0    NaN    NaN
4               5       0.0     3.0  35.000000    0.0    NaN    NaN
...           ...       ...     ...        ...    ...    ...    ...
1777          887       NaN     NaN  29.699118    NaN    0.0  13.00
1778          888       NaN     NaN  29.699118    NaN    0.0  30.00
1779          889       NaN     NaN  29.699118    NaN    2.0    NaN
1780          890       NaN     NaN  29.699118    NaN    0.0  30.00
1781          891       NaN     NaN  29.699118    NaN    0.0   7.75

[1782 rows x 7 columns]

### 3. (c) Survived, Pclass, SibSP는 결측치를 갖는 데이터를 제거하고 Parch와 Fare 피처는 제거하세요.

In [460]:
train = train.drop(columns=['Parch', 'Fare'])

missing_rows = train[train['Survived'].isnull() | train['Pclass'].isnull() | train['SibSp'].isnull()].index
print(missing_rows)

train = train.drop(missing_rows)
train

Index([ 891,  892,  893,  894,  895,  896,  897,  898,  899,  900,
       ...
       1772, 1773, 1774, 1775, 1776, 1777, 1778, 1779, 1780, 1781],
      dtype='int64', length=891)


PassengerId  Survived  Pclass        Age  SibSp
0              1       0.0     3.0  22.000000    1.0
1              2       1.0     1.0  38.000000    1.0
2              3       1.0     3.0  26.000000    0.0
3              4       1.0     1.0  35.000000    1.0
4              5       0.0     3.0  35.000000    0.0
..           ...       ...     ...        ...    ...
886          887       0.0     2.0  27.000000    0.0
887          888       1.0     1.0  19.000000    0.0
888          889       0.0     3.0  29.699118    1.0
889          890       1.0     1.0  26.000000    0.0
890          891       0.0     3.0  32.000000    0.0

[891 rows x 5 columns]

### 4.(a) 학습 데이터와 테스트 데이터를 3:1로 나누세요.

In [461]:
survived = np.array(train.loc[:,"Survived"])
train = train.drop(columns="Survived")
survived.shape, train.shape

((891,), (891, 4))

In [462]:
X_train, X_test, y_train, y_test = train_test_split(train, survived,test_size=0.25,random_state=1234)
# reshape 필수 (클래스 사용 안할 경우)
y_train, y_test = y_train.reshape(-1, 1), y_test.reshape(-1, 1)
X_train.shape

(668, 4)

### 4.(b) survived에 대해 로지스틱 회귀를 적용하세요.

In [463]:
from sklearn.linear_model import LogisticRegression

############ logisticregression으로 학습 및 예측

clf = LogisticRegression()
clf = clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)
y_pred

/opt/homebrew/lib/python3.11/site-packages/sklearn/utils/validation.py:767: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():
/opt/homebrew/lib/python3.11/site-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/opt/homebrew/lib/python3.11/site-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
/opt/homebrew/lib/python3.11/site-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for 

array([1., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 1.,
       1., 1., 0., 0., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 0., 1., 1.,
       0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 0., 1.,
       0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 1., 0.,
       1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0.,
       0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0.,
       1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 1., 0., 0.,
       1., 1.])

### 4.(c) 테스트 데이터셋에 대해 예측 정확도를 계산하세요.

In [464]:
y_pred = clf.predict(X_test)

print(f'정확도:{(y_test == y_pred).mean() * 100: .2f}%')

정확도: 54.66%


/opt/homebrew/lib/python3.11/site-packages/sklearn/utils/validation.py:767: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():
/opt/homebrew/lib/python3.11/site-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/opt/homebrew/lib/python3.11/site-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):


### 4.(d) 선형 모델의 계수들과 절편값을 확인하세요.

In [465]:
print(f'절편: {clf.intercept_[0]}')
print(f'계수: {clf.coef_[0]}')

절편: 3.306289882021942
계수: [-9.47140734e-05 -1.10316878e+00 -4.14196723e-02 -1.33671079e-01]


## 라쏘회귀 (당뇨데이터 활용, diabete)

In [466]:
from sklearn.linear_model import LassoCV, Lasso
from sklearn.pipeline import Pipeline

### 5.(a) 당뇨 데이터를 데이터프레임 형태로 불러와서, 2:1로 학습데이터와 테스트 데이터로 나누세요.

In [467]:
from sklearn.datasets import load_diabetes

X, y = load_diabetes(as_frame=True, return_X_y=True)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=1/3,random_state=1234)

### 5.(b) Standardscaler와 LassoCV를 pipeline 객체로 생성하세요. (LassoCV의 교차검증은 5회, alpha 값은 1이상 100 이하의 정수들로 하세요.)

In [468]:
scaler = StandardScaler()
reg    = LassoCV(alphas=np.arange(1,101),cv=5)
pipe   = Pipeline(steps=[("scaler", scaler), ("reg", reg)])
pipe

Pipeline(steps=[('scaler', StandardScaler()),
                ('reg',
                 LassoCV(alphas=array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100]),
                         cv=5))])

### 6.(a) 당뇨데이터의 age,sex,bmi,bp 피처에 대해서만, pipeline 객체를 통해서 라쏘회귀를 진행하세요.

In [469]:
X_train, X_test = X_train.loc[:,["age","sex","bmi","bp"]], X_test.loc[:,["age","sex","bmi","bp"]]
pipe = pipe.fit(X_train, y_train)

y_train_pred = pipe.predict(X_train)
y_train_pred

/opt/homebrew/lib/python3.11/site-packages/sklearn/utils/validation.py:767: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():
/opt/homebrew/lib/python3.11/site-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/opt/homebrew/lib/python3.11/site-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
/opt/homebrew/lib/python3.11/site-packages/sklearn/utils/validation.py:767: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  i

array([146.51110715, 162.25824225, 111.52429588, 261.08438646,
       223.27018304, 149.5733413 , 137.8512549 , 197.9512194 ,
        93.64610555, 106.28214438,  89.90299159, 150.20306183,
       186.12465241, 244.37923541, 131.33909484, 208.73634573,
       131.35412116, 146.09983484, 113.36738545,  95.19295913,
       190.45542104, 191.52694809, 147.90344997, 143.40426157,
       175.82394564, 227.85503077, 192.83850313, 177.71294113,
       159.94958772, 125.55511156, 102.28011033,  45.13934815,
        88.8925844 , 206.28598608,  77.13106907, 122.853301  ,
       124.57362831, 105.48905282, 150.59541109, 163.27601583,
       138.43563371,  78.61516292,  72.88088532,  98.33507709,
       129.48461119, 185.10539672, 111.84772808, 174.35610697,
       112.42596656, 115.38583317, 121.07499767, 229.04657201,
        65.09377982, 117.94534034, 164.09208104,  98.22181403,
       140.1017913 ,  65.78205452, 205.31079741, 165.05127994,
       178.90437083, 224.75939686, 139.63635972, 122.59

### 6.(b) 테스트 데이터 셋의 mean_absolute_error를 나타내세요.

In [470]:
y_pred = pipe.predict(X_test)
print(f'MAE:{(np.abs(y_pred - y_test)).mean(): .3f}')

MAE: 48.549


/opt/homebrew/lib/python3.11/site-packages/sklearn/utils/validation.py:767: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():
/opt/homebrew/lib/python3.11/site-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/opt/homebrew/lib/python3.11/site-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):


### 6.(c) 결과로 얻은 선형모델 계수들과 절편의 값을 확인하세요.

In [471]:
print(f'절편: {reg.intercept_}')
print(f'계수: {reg.coef_}')

절편: 150.85714285714286
계수: [ 0.16801308 -5.93123842 36.61337794 20.13401954]


### 6.(d) 가장 좋은 성능을 보이는 alpha값을 얻으세요.

In [472]:
print('최적의 alpha:', reg.alpha_)

최적의 alpha: 1
