In [5]:
import torch

## 텐서 생성

In [3]:
print(torch.Tensor())   # 텐서의 기본형, 텐서 인스턴스를 생성하는 클래스
# 인스턴스를 생성하므로 값을 입력하지 않는 경우 비어있는 텐서 생성

tensor([])


In [4]:
print(torch.tensor())

TypeError: tensor() missing 1 required positional arguments: "data"

In [6]:
print(torch.tensor([1,2,3]))
print(torch.Tensor([[1,2,3], [4,5,6]]))
print(torch.LongTensor([1,2,3]))
print(torch.FloatTensor([1,2,3]))
# !자료형이 명확히 표현되는 torch.Tensor() 사용하기!

tensor([1, 2, 3])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([1, 2, 3])
tensor([1., 2., 3.])
